# Generated by Django 6.0.4 on 2026-04-12 12:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=250.0, help_text='Base price for an event within the free-delivery radius.', max_digits=10)),
                ('band_1_miles', models.PositiveIntegerField(default=25, help_text='End of free band (miles).')),
                ('band_2_miles', models.PositiveIntegerField(default=50)),
                ('band_3_miles', models.PositiveIntegerField(default=100)),
                ('band_4_miles', models.PositiveIntegerField(default=200, help_text='Max radius.')),
                ('band_1_price', models.DecimalField(decimal_places=2, default=0, help_text='0–25 mi surcharge (usually 0).', max_digits=10)),
                ('band_2_price', models.DecimalField(decimal_places=2, default=50.0, help_text='25–50 mi surcharge.', max_digits=10)),
                ('band_3_price', models.DecimalField(decimal_places=2, default=120.0, help_text='50–100 mi surcharge.', max_digits=10)),
                ('band_4_price', models.DecimalField(decimal_places=2, default=250.0, help_text='100–200 mi surcharge.', max_digits=10)),
                ('max_radius_miles', models.PositiveIntegerField(default=200)),
                ('hold_duration_minutes', models.PositiveIntegerField(default=5, help_text='How long a date hold lasts before auto-release.', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_guests', models.PositiveIntegerField(default=10)),
                ('max_guests', models.PositiveIntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Event Configuration',
                'verbose_name_plural': 'Event Configuration',
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='held', max_length=20)),
                ('hold_token', models.CharField(db_index=True, help_text='Client-side token to identify the holder.', max_length=64, unique=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text='When the hold auto-releases.', null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True)),
                ('distance_miles', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('timing_start', models.TimeField(blank=True, null=True)),
                ('timing_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'status'], name='events_even_date_e11c6c_idx'), models.Index(fields=['hold_token'], name='events_even_hold_to_5eacf5_idx')],
            },
        ),
    ]
