# Generated by Django 6.0.4 on 2026-04-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name, e.g. "Lunch Service", "Evening Service".', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_bookings_per_day', models.PositiveIntegerField(default=1, help_text='Max simultaneous bookings for this slot on a single day (usually 1).')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='The time slot for this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.timeslot'),
        ),
    ]
