# Generated by Django 6.0.4 on 2026-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_timeslot_eventbooking_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='max_bookings_per_day',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available_days',
            field=models.CharField(blank=True, default='', help_text='Comma-separated day numbers (0=Mon, 6=Sun). Empty = every day. e.g. "0,1,2,3,4" for weekdays.', max_length=20),
        ),
    ]
